/**
 * generated by Xtext 2.12.0
 */
package m1ice.ui.contentassist;

import m1ice.ui.contentassist.AbstractSpotifyRequetorProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SpotifyRequetorProposalProvider extends AbstractSpotifyRequetorProposalProvider {
}
