/*
 * generated by Xtext 2.12.0
 */
package m1ice


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SpotifyRequetorRuntimeModule extends AbstractSpotifyRequetorRuntimeModule {
}
