/**
 * generated by Xtext 2.12.0
 */
package m1ice.tests;

import com.google.inject.Inject;
import m1ice.tests.SpotifyRequetorInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import spotify_Requetor.CommandManager;

@RunWith(XtextRunner.class)
@InjectWith(SpotifyRequetorInjectorProvider.class)
@SuppressWarnings("all")
public class SpotifyRequetorParsingTest {
  @Inject
  private ParseHelper<CommandManager> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final CommandManager result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      Assert.assertTrue(result.eResource().getErrors().isEmpty());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
