/*
 * generated by Xtext 2.12.0
 */
package m1ice.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SpotifyRequetorWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSpotifyRequetorWebModule extends DefaultWebModule {

}
