/*
 * generated by Xtext 2.12.0
 */
package m1ice.ui.tests;

import com.google.inject.Injector;
import m1ice.spotifyRequetor.ui.internal.SpotifyRequetorActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SpotifyRequetorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpotifyRequetorActivator.getInstance().getInjector("m1ice.SpotifyRequetor");
	}

}
