/**
 * generated by Xtext 2.12.0
 */
package m1ice.ide;

import m1ice.ide.AbstractSpotifyRequetorIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SpotifyRequetorIdeModule extends AbstractSpotifyRequetorIdeModule {
}
