/**
 * generated by Xtext 2.12.0
 */
package m1ice.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import m1ice.SpotifyRequetorRuntimeModule;
import m1ice.SpotifyRequetorStandaloneSetup;
import m1ice.ide.SpotifyRequetorIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SpotifyRequetorIdeSetup extends SpotifyRequetorStandaloneSetup {
  @Override
  public Injector createInjector() {
    SpotifyRequetorRuntimeModule _spotifyRequetorRuntimeModule = new SpotifyRequetorRuntimeModule();
    SpotifyRequetorIdeModule _spotifyRequetorIdeModule = new SpotifyRequetorIdeModule();
    return Guice.createInjector(Modules2.mixin(_spotifyRequetorRuntimeModule, _spotifyRequetorIdeModule));
  }
}
