/**
 * generated by Xtext 2.12.0
 */
package m1ice.web;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class SpotifyRequetorWebSetup /* implements SpotifyRequetorStandaloneSetup  */{
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules2 is undefined"
      + "\nSpotifyRequetorRuntimeModule cannot be resolved."
      + "\nSpotifyRequetorIdeModule cannot be resolved."
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
