/**
 * generated by Xtext 2.12.0
 */
package m1ice.web;

import m1ice.web.AbstractSpotifyRequetorWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class SpotifyRequetorWebModule extends AbstractSpotifyRequetorWebModule {
}
