/*
 * generated by Xtext 2.12.0
 */
package m1ice.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpotifyRequetorScopeProvider extends DelegatingScopeProvider {
}
