/**
 * generated by Xtext 2.12.0
 */
package m1ice.ui;

import m1ice.ui.AbstractSpotifyRequetorUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SpotifyRequetorUiModule extends AbstractSpotifyRequetorUiModule {
  public SpotifyRequetorUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
