/**
 * generated by Xtext 2.12.0
 */
package m1ice;

import m1ice.AbstractSpotifyRequetorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SpotifyRequetorRuntimeModule extends AbstractSpotifyRequetorRuntimeModule {
}
