/**
 * generated by Xtext 2.12.0
 */
package m1ice;

import m1ice.SpotifyRequetorStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SpotifyRequetorStandaloneSetup extends SpotifyRequetorStandaloneSetupGenerated {
  public static void doSetup() {
    new SpotifyRequetorStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
