/**
 * generated by Xtext 2.12.0
 */
package m1ice.validation;

import m1ice.validation.AbstractSpotifyRequetorValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SpotifyRequetorValidator extends AbstractSpotifyRequetorValidator {
}
