/*
 * generated by Xtext 2.12.0
 */
package m1ice.parser.antlr;

import com.google.inject.Inject;
import m1ice.parser.antlr.internal.InternalSpotifyRequetorParser;
import m1ice.services.SpotifyRequetorGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SpotifyRequetorParser extends AbstractAntlrParser {

	@Inject
	private SpotifyRequetorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSpotifyRequetorParser createParser(XtextTokenStream stream) {
		return new InternalSpotifyRequetorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CommandManager";
	}

	public SpotifyRequetorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SpotifyRequetorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
