/*
 * generated by Xtext 2.12.0
 */
package m1ice.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpotifyRequetorAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("m1ice/parser/antlr/internal/InternalSpotifyRequetor.tokens");
	}
}
